# See: https://taskfile.dev/api/

version: "3"

tasks:
  migrate:
    desc: "Migrate database"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
    
  migrate_tests:
    desc: "Run tests migrate"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test